saya25_louvre_accueil :
    path:     /accueil
    defaults: { _controller: saya25LouvreBundle:Ticket:accueil }

saya25_louvre_billetterie :
    path:     /billetterie
    defaults: { _controller: saya25LouvreBundle:Ticket:billetterie}

saya25_louvre_deletebillet :
    path:     /deletebillet
    defaults: { _controller: saya25LouvreBundle:Ticket:deletebillet}

saya25_louvre_commande :
    path:     /commande
    defaults: { _controller: saya25LouvreBundle:Ticket:commande}

saya25_louvre_paiement :
    path:     /paiement
    defaults: { _controller: saya25LouvreBundle:Ticket:paiement}

saya25_louvre_confirmation :
    path:     /confirmation
    defaults: { _controller: saya25LouvreBundle:Ticket:confirmation}

saya25_louvre_contact :
    path:     /contact
    defaults: { _controller: saya25LouvreBundle:Ticket:contact}

saya25_louvre_mentionslegales :
    path:     /mentionslegales
    defaults: { _controller: saya25LouvreBundle:Ticket:mentionslegales}







