services:
#    saya25_louvre.example:
#        class: saya25\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    core.back:
        class: saya25\LouvreBundle\Service\Back
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@app.price", "@router"]


    app.price:
        class: saya25\LouvreBundle\Service\Price

