<?php

namespace saya25\LouvreBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBilletWithCommandeByDate()
    {
        return $this->createQueryBuilder('b')
            ->innerJoin('b.commande', 'commande')
            ->addSelect('commande')
            ->where('commande.dateEntree = :date')
            ->setParameter('date', new \DateTime('now'))
            ->getQuery()
            ->getResult();
    }

    public function getBilletWithCommandeDate($date){

        return $this->createQueryBuilder('b')
            ->innerJoin('b.commande', 'commande')
            ->addSelect('commande')
            ->where('commande.dateEntree = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();

    }


}
